### ISSUE TITLE
resourcepacks not following given order 

### ISSUE THREAD

**Issue by VaporeonScripts** [JTK222/Global-Packs#60]
![image](https://github.com/user-attachments/assets/1792eb68-448e-4219-a8bc-ed45517e3afb)
the lowest should be first, altough it looks like this
![image](https://github.com/user-attachments/assets/d6814251-c247-4153-9955-121f9ba5f2bf)

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1

**Comment by DarthCaesium** [comment]
Can confirm this issue too. Also 1.21.1 on NeoForge.

**Comment by Dreytac** [comment]
Just ran into this issue myself. Global Packs v1.16.2 on Forge v1.20.1.

For the moment I've just prefixed the filenames with the order "1-, 2-, 3- etc".

**Comment by JTK222** [comment]
Fixed in 21.0.3, will soonish be backported to some older versions

**Comment by VaporeonScripts** [comment]
was this  bug fixed for 1.21.1 neoforge?

**Comment by VaporeonScripts** [comment]
![Image](https://github.com/user-attachments/assets/7ecdb148-daa3-4abc-ab26-60d9869bef6c)
this is clearly not fixed...

![Image](https://github.com/user-attachments/assets/01fb5a49-a3e0-4547-bdd2-a513e05dbbe6)

**Comment by VaporeonScripts** [comment]
alright, it works by inverting that order, next time just say that the last element would be the one with the highest priority...

**Comment by VaporeonScripts** [comment]
doesnt' work after relaunching somehow, the order isn't respected

**Comment by VaporeonScripts** [comment]
alr, looks like that after removing paxi it needs to reboot 2 times to apply global packs correctly, the issue seems fixed
